[package]
name = "xilem_colors"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
palette = "0.7.6"
peniko = "0.1.1"

[lints]
workspace = true
